CyclomaticComplexity:
  Max: 10
LineLength:
  Max: 110
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
MethodLength:
  Enabled: false
Style/SymbolArray:
  Enabled: false
