CyclomaticComplexity:
  Enabled: false
LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
MethodLength:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Style/SymbolArray:
  Enabled: false
